theme: null

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

title : "Move to Heigher"
description: "KodaGrammer's Page for moving to heigher."
url : "https://kodagrammer.github.io/"
baseurl : ""
lang : "en"

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
